vich_uploader:
  db_driver: orm

  mappings:
    prestations:
      uri_prefix: /images/prestations
      upload_destination: '%kernel.project_dir%/public/images/prestations'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


    pieces_jointes:
      uri_prefix: /images/prestations
      upload_destination: '%kernel.project_dir%/public/images/prestations'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer